### ISSUE TITLE
Need to support proxy options for posting to rooms

### ISSUE THREAD

**Issue by desktophero** [jmccann/drone-hipchat#19]
Configuring proxy options for notifications is needed to allow posts to the APIs. Otherwise, various errors can happen but are not raised as part of the build logs.

**Comment by bradrydzewski** [comment]
can you clarify this issue? are you asking to set HTTP_PROXY environment variables? If yes, these can be set adding an environment block to your plugin:

```
notify:
  hipchat:
    ...
    environment:
      - HTTP_PROXY=...
```

or alternatively you can define these variables at the server level, which will then propagate the values down to all build and plugin containers. See http://readme.drone.io/setup/proxy_network/

**Comment by desktophero** [comment]
I've tried multiple iterations on injecting env variables with that structure. The result is always:

`x509: certificate signed by unknown authority\n[info] build failed (exit code 1)`

That's from our proxy doing a MITM SSL verification. The HTTP_PROXY/HTTPS_PROXY/http_proxy/https_proxy env variables are not being honored as I redirect to a child proxy. That child proxy isn't showing any requests from the IP running drone. I do see other traffic, from other plugins in drone, connecting to the child-proxy.

I'm a n00b to Go but when I look through the Send logic in the hipchat.go file, I didn't see/missed the `proxy` checking and config.

**Comment by desktophero** [comment]
I'm also setting all four env variables (lcase, ucase). I've also moved the env variables from `notify` to `build` - just to see if that mattered.

**Comment by bradrydzewski** [comment]
Go loads the proxy environment variables automatically into the `http.DefaultTransport` which is generally used by `http.DefaultClient`:
https://github.com/golang/go/blob/f459660cb85abd504845f93fdb65b1932bd6ac37/src/net/http/transport.go#L37

That being said, It is possible for a package (like the go hipchat package we are importing) to use a custom Transport or Client in which case these variables could get ignored.

**Comment by desktophero** [comment]
I wasn't able to get notifications to HipChat using this plugin until I was able to get the proxy admin to update policies. The proxy I defined in `http_proxy` (a child proxy I control) received no notifications or attempts to pass to the parent proxy. 

Post parent proxy policy being applied (how's that for alliteration!), the notifications worked fine.

For other drone plugins, the environment stanza in `.drone.yml` appears to be honored fine (not the plugins, but the plugins I've tried. I can collapse that to an actual list if helpful.

One other thing to pull into this issues: including `no_proxy` from env variables. Might be a moot thing for HipChat notifications (generally speaking, you're posting to an instance of HipChat - on-prem or SaaS, and not a mix) but no reason to not encourage consistent plugin development, docs, and consumption.

**Comment by desktophero** [comment]
I just haven't had time to go deeper into the plugin. If there's something I can execute to help flush out config options of the hipchat package being imported, let me know. Otherwise, there's still a need for this at least based on the actions I needed to make the proxy be a-okay with the setup. 

Without giving specifics, I can try to write up the policy definition in our parent proxy but the plugin isn't honoring the environment variables. To help protect my customers of Drone CI internally, I'd like to make sure this doesn't go back to `broken` internally with 0.5. How can I help flush out details to make usage behind a proxy with this plugin better?

**Comment by bradrydzewski** [comment]
It looks like this plugin is using the default http client:
https://github.com/drone-plugins/drone-hipchat/blob/master/hipchat.go#L49

The default http client uses the default transport which uses http_proxy variables:

> DefaultTransport is the default implementation of Transport and is used by DefaultClient. It establishes network connections as needed and caches them for reuse by subsequent calls. It uses HTTP proxies as directed by the $HTTP_PROXY and $NO_PROXY (or $http_proxy and $no_proxy) environment variables.

You should be able to test the plugin in isolation using `docker run`:
https://github.com/drone-plugins/drone-hipchat#example-1

You can use the `-e HTTP_PROXY=...` option with `docker run` to pass the environment variables. I haven't used the proxy personally but I know this was something important to @donny-dont and last I knew it was working for them, but perhaps he can verify.

Maybe testing in isolation will help? Also you can compile your own version of the plugin and dump the environment variables just to verify: `println(os.Getenv("HTTP_PROXY"))` to verify they are being passed

**Comment by jmccann** [comment]
If still having the issue feel free to reopen.
