### ISSUE TITLE
DRONE_BUILD_STATUS

### ISSUE THREAD

**Issue by Mazon** [jmccann/drone-hipchat#24]
When my steps fail before and i have set

`when:
  status: [ failure ]`

on drone-hipchat , it is triggered but i never get DRONE_BUILD_STATUS set to build.status, ive tried 
setting build.status: ${DRONE_BUILD_STATUS} but not sure, think i am doing something wrong. I can see in hipchat that build.status is always printing success. Can see that prob means empty var.

**Comment by tobias-graf-p** [comment]
@Mazon I also experience that ${DRONE_BUILD_STATUS} always prints "success" while {{build.status}} prints either "success" or "failure" depending of the actual result of the pipeline. I see you closed this issue yourself. Did you find the reason or a solution for this?
