### ISSUE TITLE
Hipchat Self Signed Certificate Issue

### ISSUE THREAD

**Issue by ghost** [jmccann/drone-hipchat#25]
This is not really an issue with your awesome plugin (thank you btw), but I was hoping you could please help point me in the right direction. We host our own hipchat and it is protected with a self signed certificate so when I try notify from drone i get:

```
time="2017-11-09T03:44:56Z" level=info msg="Drone Hipchat Plugin Version" Revision=d1684a32969b7b736aa73413105a99671e7ab7b0 
0s
2
Post https://hipchat.dev.tsbbank.co.nz/v2/room/97/notification?auth_token=euSOIE6CEozaOsxbA4hHXDycSMkjvUAIQF6VYon6: x509: certificate signed by unknown authority
```

I have trawled for an answer everywhere and cannot seem to come right, please help?

Thanks in advance!!

**Comment by bradrydzewski** [comment]
Hi Justin,

One option could be to update the plugin to accept a `skip_verify` flag and then adjust the hipchat client to use a custom http.Client with TLS verification disabled when true.

```diff
// Client represents the HipChat client.
type Client struct {
	URL string
+	SkipVerify bool
}

// NewClient returns a new HipChat Client.
-func NewClient(url, room, token string) *Client {
+func NewClient(url, room, token string, sslverify bool) *Client {
	if url == "" {
		url = defaultURL
	}
	return &Client{
		URL: fmt.Sprintf(notifyPath, url, room, token),
+		SkipVerify: sslverify,
	}
}

---
+	client := &http.Client{
+		Transport: &http.Transport{
+			Proxy: http.ProxyFromEnvironment,
+			TLSClientConfig: &tls.Config{InsecureSkipVerify: c.SkipVerify},
+			DialContext: (&net.Dialer{
+				Timeout:   30 * time.Second,
+				KeepAlive: 30 * time.Second,
+				DualStack: true,
+			}).DialContext,
+			MaxIdleConns:          100,
+			IdleConnTimeout:       90 * time.Second,
+			TLSHandshakeTimeout:   10 * time.Second,
+			ExpectContinueTimeout: 1 * time.Second,
+		}
+	}

-	resp, err := http.Post(c.URL, "application/json", buf)
+	resp, err := client.Post(c.URL, "application/json", buf)

---
```

Or alternatively you might need to mount the certificate from the host machine into the plugin. Luckily this is something @jmccann has quite a bit of experience with, so he will be able to advise on the best approach :)

**Comment by ghost** [comment]
Thanks @bradrydzewski, you are a king! Not really capable on Go yet and would also prefer to not muddy the plugin water with my limited knowledge, hopefully @jmccann can suggest a way to mount/trust the cert into the plugin, otherwise will attempt your suggestion.

**Comment by ghost** [comment]
Hi @bradrydzewski. 

I tried your changes, was pretty straightforward thanks. I had to do an additional codesteps in the plugin.go to pick up the properties to send to new client:

```go
Config struct {
		Url       string
		AuthToken string
		Room      string
		From      string
		Notify    bool
		Template  string
		SslVerify bool
	}
```

and 

```go
client := NewClient(
		p.Config.Url,
		p.Config.Room,
		p.Config.AuthToken,
		p.Config.SslVerify,
	)
```

and then in hipchat.go I had to include some imports:

```go
import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"net"
	"crypto/tls"
	"time"
)
```

and also just needed to include a comma in the code you provided:

```go
client := &http.Client {
            Transport: &http.Transport{
                Proxy: http.ProxyFromEnvironment,
                TLSClientConfig: &tls.Config{InsecureSkipVerify: c.SkipVerify},
                DialContext: (&net.Dialer{
                    Timeout:   30 * time.Second,
                    KeepAlive: 30 * time.Second,
                    DualStack: true,
                }).DialContext,
                MaxIdleConns:          100,
                IdleConnTimeout:       90 * time.Second,
                TLSHandshakeTimeout:   10 * time.Second,
                ExpectContinueTimeout: 1 * time.Second,
            },
        }
```

But it doesnt seem to have worked, any other ideas? I am getting the same:
x509: certificate signed by unknown authority

**Comment by bradrydzewski** [comment]
Sorry my example wasn't fully complete. There are some additional steps that you didn't mention (not sure if you tried them) but you would need to read the parameter to disable ssl verification from the environment / yaml. You can register this parameter like this:

```diff
		cli.BoolFlag{
			Name: "skip_verify",
			EnvVar: "PLUGIN_SKIP_VERIFY",
		},
```

and then read the parameter and set in the structure:

```diff
		Config: Config{
			Url:       c.String("url"),
			AuthToken: c.String("auth_token"),
			Room:      c.String("room"),
			From:      c.String("from"),
			Notify:    c.Bool("notify"),
			Template:  c.String("template"),
+			SslVerify: c.Bool("skip_verify"),
		},
```

and then in your yaml:

```diff
pipeline:
  notify:
    image: plugins/hipchat
+   skip_verify: true
```

or if you are testing the plugin from the command line you would pass environment variable `PLUGIN_SKIP_VERIFY=true`

**Comment by ghost** [comment]
See told you you were a king :) awesome man that worked thank you so much! I was tinkering around those parts as I had hardcoded the InsecureSkipVerify value to test that it was working and it did, so I realised it must be something to do with loading the ssl verify property properly. 

Also in our example at some point it switched from sslverify to SkipVerify, so I just standardised everything to skip_ssl_verify in the property and SkipSslVerify in the code for sanities sake.

**Comment by jmccann** [comment]
@justiniantaylor Mind submitting a PR for the code changes you did?
